<?php
declare(strict_types=1);

// Bevwire SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

BevwireUtility::setRegistrar(function (BevwireUtility $u): void {
    $u->clean = [BevwireClean::class, 'call'];
    $u->done = [BevwireDone::class, 'call'];
    $u->make_error = [BevwireMakeError::class, 'call'];
    $u->feature_add = [BevwireFeatureAdd::class, 'call'];
    $u->feature_hook = [BevwireFeatureHook::class, 'call'];
    $u->feature_init = [BevwireFeatureInit::class, 'call'];
    $u->fetcher = [BevwireFetcher::class, 'call'];
    $u->make_fetch_def = [BevwireMakeFetchDef::class, 'call'];
    $u->make_context = [BevwireMakeContext::class, 'call'];
    $u->make_options = [BevwireMakeOptions::class, 'call'];
    $u->make_request = [BevwireMakeRequest::class, 'call'];
    $u->make_response = [BevwireMakeResponse::class, 'call'];
    $u->make_result = [BevwireMakeResult::class, 'call'];
    $u->make_point = [BevwireMakePoint::class, 'call'];
    $u->make_spec = [BevwireMakeSpec::class, 'call'];
    $u->make_url = [BevwireMakeUrl::class, 'call'];
    $u->param = [BevwireParam::class, 'call'];
    $u->prepare_auth = [BevwirePrepareAuth::class, 'call'];
    $u->prepare_body = [BevwirePrepareBody::class, 'call'];
    $u->prepare_headers = [BevwirePrepareHeaders::class, 'call'];
    $u->prepare_method = [BevwirePrepareMethod::class, 'call'];
    $u->prepare_params = [BevwirePrepareParams::class, 'call'];
    $u->prepare_path = [BevwirePreparePath::class, 'call'];
    $u->prepare_query = [BevwirePrepareQuery::class, 'call'];
    $u->graphql_body = [BevwireGraphql::class, 'body'];
    $u->graphql_errors = [BevwireGraphql::class, 'errors'];
    $u->result_basic = [BevwireResultBasic::class, 'call'];
    $u->result_body = [BevwireResultBody::class, 'call'];
    $u->result_headers = [BevwireResultHeaders::class, 'call'];
    $u->transform_request = [BevwireTransformRequest::class, 'call'];
    $u->transform_response = [BevwireTransformResponse::class, 'call'];
});
